### ISSUE TITLE
panicked at time.rs:187:9

### ISSUE THREAD

**Issue by ildar** [dbrgn/pinetime-rtic#5]
I'm doing P8 watch port: https://github.com/ildar/pinetime-rtic . I have no original PineTime. But testing the pinetime-rtic on P8 panics:
```
Initializing…
Setting backlight brightness to 1
Bluetooth device address: 10:69:c3:9c:12:56(Random)
panicked at '4293796891µs between instants 1.572403s and 401.998ms', /usr/src/.cargo/git/checkouts/rubble-1acc4a403ea48878/78a9172/rubble/src/time.rs:187:9
```

**Comment by dbrgn** [comment]
I haven't done anything with the PineTime for a while now, and probably won't be of much help.

Seems to be some problem with a timer implementation? I'm not sure. Try take a look at that line of code inside rubble. Maybe try upgrading Rubble.
